### ISSUE TITLE
Error thrown on ke.inspection.expose(model)

### ISSUE THREAD

**Issue by AshaB89** [lucasdavid/keras-explainable#1]
ValueError: A valid layer couldn't be inferred from the name=`None`, klass=`(<class 'keras.layers.reshaping.flatten.Flatten'>, <class 'keras.layers.pooling.base_global_pooling1d.GlobalPooling1D'>, <class 'keras.layers.pooling.base_global_pooling2d.GlobalPooling2D'>, <class 'keras.layers.pooling.base_global_pooling3d.GlobalPooling3D'>)` and properties=`None`. Make sure these attributes correctly reflect a layer in the model.

Can you explain what is the problem?

**Comment by lucasdavid** [comment]
The library is unsuccessful at finding the pooling layer (e.g. Flatten, Max/AvgPooling), which marks the end of the positional signal. It needs to know this in CAM methods, as the classification importance is computed with respect to each pixel in the positional signal.

So, can you share which method are you trying to use and the architecture you are employing (how is your model)?
